version: 2
jobs:
  build:
    working_directory: /opt/rime_ci
    docker:
      - image: satellitex/rime-ci:latest
    steps:
      - checkout
      - run:
          name: all-build
          command: |
            cd test_rime_project
            ./all-test.sh